print("######################")
print("3.1")
print("######################")
# Эта программа считывает два числа и выводит их сумму:
a = int(input())
b = int(input())
c = int(input())
print("Итог: ", a + b + c)
# Можете ли вы изменить её, чтобы она складывала три числа?
print("######################")
print("3.2")
print("######################")
# Числа b и h можно считывать так:
b = int(input())
h = int(input())
# Выводите результат через print()

print("Итог: ", 0.5 * b * h)
print("######################")
print("3.3")
print("######################")
apelsini = int(input())
deti = int(input())

print("Итог: ", apelsini // deti)
print("######################")
print("3.4")
print("######################")
n = int(input())
hours = n % (60 * 24) // 60
minutes = n % 60
print(hours, minutes)
print("######################")
print("3.5")
print("######################")
string1 = input()
print("Hello,", string1)
print("######################")
print("3.6")
print("######################")
nn = int(input())
print('The next number for the number ' + str(n) + ' is ' + str(n + 1) + '.')
print('The previous number for the number ' + str(n) + ' is ' + str(n - 1) + '.')
print("######################")
print("3.7")
print("######################")
z = int(input())
x = int(input())
y = int(input())
print("Итог: ", z // 2 + x // 2 + y // 2 + z % 2 + x % 2 + y % 2)
print("######################")
print("3.8")
print("######################")
u = int(input())
i = int(input())
o = int(input())
p = int(input())
print("Итог: ", (2 * o + (2 * p - 1) * u + 2 * (p - 1) *  i))
